import math

class Config:
    LIDAR_MIN_ANGLE = -2.03
    LIDAR_MAX_ANGLE = 2.03

    SCAN_LINE_SEGMENT_LENGTH = 8
    LINE_SLOPE_JOIN_THRESH = math.radians(18)
    LINE_GAP_JOIN_THRESH = 0.4
    SCAN_POINT_MAX_DENSITY = 0.03
    SCAN_POINT_OUTLIER_THRESH = 0.1

    LINE_CORNER_ANGLE_THRESH = math.radians(10)

    DEPTH_CAMERA_WIDTH = 640
    DEPTH_CAMERA_HEIGHT = 480
    DEPTH_BOX_Z_ADJUST = 0.02
    CAMERA_EXCLUDE_EDGES_X = 20
    CAMERA_EXCLUDE_EDGES_Y = 20

def get_config() -> Config:
    cfg = Config()
    return cfg